{% set name = "ndscope" %}
{% set version = "0.14.3" %}

package:
  name: ndscope
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6429d45b6cdc1bff347270d54831d269e43b7df30959f90556beff10cee345f8

build:
  entry_points:
    - ndscope = ndscope.__main__:main
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - cairosvg
    - gpstime
    - h5py
    - matplotlib-base
    - numpy
    - pyqtgraph
    - python
    - python-dateutil
    - python-nds2-client
    - pyyaml
    - pyqt >=5
    - qtpy
    - setproctitle

test:
  requires:
    - pip
    - pytest
  imports:
    - ndscope
  commands:
    - pip check
    - python -m pytest --pyargs ndscope
    - ndscope --help

about:
  home: https://git.ligo.org/cds/ndscope
  dev_url: https://git.ligo.org/cds/ndscope
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Next-generation NDS oscilloscope
  description: |
    View time series data of channels from LIGO network data servers
    (NDS) with an intuitive GUI interface.  Features include:
    * online and offline data viewing
    * intuitive mouse gestures for pan and zoom
    * auto-retrieval of new data as the time range expands
    * auto-switching from raw data to second/minute trends depending
      on time scale
    * supports both NDS1 and NDS2 protocols, for viewing both in
      LIGO/Kagra control rooms as well as anywhere else in the world

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
