{% set name = "ndscope" %}
{% set version = "0.18.0" %}

package:
  name: ndscope
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0aea22d8f3587e315fd16dc9b0a45eaf0d98ba07cea9168e3f4b0054a8f01bd3

build:
  entry_points:
    - ndscope = ndscope.__main__:main
    - ndschans = ndscope.channel_select:main
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - setuptools-scm
  run:
    - cairosvg
    - gpstime
    - h5py
    - matplotlib-base
    - numpy
    - pyqtgraph
    - python >=3.7
    - python-dateutil
    - python-nds2-client
    - pyyaml
    - pyqt >=5
    - qtpy
    - setproctitle

test:
  requires:
    - pip
    - pytest
    - pytest-console-scripts
  imports:
    - ndscope
  commands:
    - pip check
    - python -m pytest --pyargs ndscope
    - ndscope --help
    - ndschans --help

about:
  home: https://git.ligo.org/cds/ndscope
  dev_url: https://git.ligo.org/cds/ndscope
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Next-generation NDS oscilloscope
  description: |
    View time series data of channels from LIGO network data servers
    (NDS) with an intuitive GUI interface.  Features include:
    * online and offline data viewing
    * intuitive mouse gestures for pan and zoom
    * auto-retrieval of new data as the time range expands
    * auto-switching from raw data to second/minute trends depending
      on time scale
    * supports both NDS1 and NDS2 protocols, for viewing both in
      LIGO/Kagra control rooms as well as anywhere else in the world

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
