{% set name = "ndscope" %}
{% set version = "0.15.1" %}

package:
  name: ndscope-base
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15a96ca4a3b4d97570e6750f9f6179f832673f7e97e2edebf32a1872d8b3f46c

build:
  entry_points:
    - ndscope = ndscope.__main__:main
    - ndschans = ndscope.channel_select:main
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - setuptools-scm
  run:
    - cairosvg
    - gpstime
    - h5py
    - matplotlib-base
    - numpy
    - pyqtgraph
    - python >=3.7
    - python-dateutil
    - python-nds2-client
    - pyyaml
    - qtpy
    - setproctitle

test:
  requires:
    - pip
  commands:
    # check requirements
    - python -m pip check

outputs:
  - name: ndscope-base
  - name: ndscope
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage('ndscope-base', max_pin='x.x.x.x') }}
        - pyqt
    test:
      requires:
        - pytest
        - setuptools
      commands:
        # run test suite
        - python -m pytest --pyargs ndscope
        # check entry points
        - ndscope --help
        - ndschans --help

about:
  home: https://git.ligo.org/cds/ndscope
  dev_url: https://git.ligo.org/cds/ndscope
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Next-generation NDS oscilloscope
  description: |
    View time series data of channels from LIGO network data servers
    (NDS) with an intuitive GUI interface.  Features include:
    * online and offline data viewing
    * intuitive mouse gestures for pan and zoom
    * auto-retrieval of new data as the time range expands
    * auto-switching from raw data to second/minute trends depending
      on time scale
    * supports both NDS1 and NDS2 protocols, for viewing both in
      LIGO/Kagra control rooms as well as anywhere else in the world

extra:
  feedstock-name: ndscope
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
